<%@ Page Title="" Language="C#" MasterPageFile="~/ADMIN/Home.master" AutoEventWireup="true" CodeFile="ViewProduct.aspx.cs" Inherits="ADMIN_ViewProduct" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style2
        {
            width: 902px;
        }
        .style3
        {
            width: 161px;
        }
        .auto-style2 {
            width: 140px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="tbl">
        <tr>
            <td class="tblhead" style="color:#eb3535;font-weight:bold;background-color:#f6c492;font-size:150%;">
                <br />
                VIEW PRODUCT -
                <asp:Label ID="lblcnt" runat="server" Font-Size="100%"></asp:Label>
            </td>
        </tr>
        <tr>
            <td>
                <table class="style2">
                    <tr>
                        <td class="auto-style2">
                            &nbsp;</td>
                        <td>
                            &nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style2">
                            &nbsp;</td>
                        <td>
                            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                                BackColor="White" BorderColor="#CC9966" BorderWidth="1px" 
                                CellPadding="4" 
                                AutoGenerateDeleteButton="False" DataKeyNames="pid" Font-Names="Times New Roman"
                                onrowdeleting="GridView1_RowDeleting" Width="856px" AllowPaging="True" 
                                onpageindexchanging="GridView1_PageIndexChanging" 
                                onselectedindexchanged="GridView1_SelectedIndexChanged" BorderStyle="Ridge" Height="477px" >
                                <Columns>
                                    <asp:CommandField EditText="" ShowDeleteButton="True">
                                    <ControlStyle Font-Bold="True" ForeColor="Red" />
                                    </asp:CommandField>
                                <asp:TemplateField HeaderText="Image">
                                <ItemTemplate>
                                <asp:Image ID="imgg" runat="server" ImageUrl='<%#Eval("Image") %>' Height="40px" Width="40px" />
                                </ItemTemplate>
                                </asp:TemplateField>

                                    <asp:BoundField DataField="pname" HeaderText="Product Name" 
                                        SortExpression="pname" />
                                    <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" />
                                    <asp:BoundField DataField="detail" HeaderText="Description" 
                                        SortExpression="detail" >
                                    <ItemStyle Width="200px" />
                                    </asp:BoundField>
                                    <asp:BoundField DataField="cname" HeaderText="Category" 
                                        SortExpression="cname" />
                                </Columns>
                                <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
                                <PagerStyle ForeColor="#330099" 
                                    HorizontalAlign="Center" BackColor="#FFFFCC" />
                                <RowStyle BackColor="White" ForeColor="#330099" />
                                <SelectedRowStyle BackColor="#FFCC66" ForeColor="#663399" Font-Bold="True" />
                                <SortedAscendingCellStyle BackColor="#FEFCEB" />
                                <SortedAscendingHeaderStyle BackColor="#AF0101" />
                                <SortedDescendingCellStyle BackColor="#F6F0C0" />
                                <SortedDescendingHeaderStyle BackColor="#7E0000" />
                            </asp:GridView>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</asp:Content>

